services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        volumes:
            - .:/techtrends
        env_file: .env


    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    celery_worker:
        build: .
        command: celery -A tech_trends worker --loglevel=info
        volumes:
            - .:/techtrends
        env_file: .env
        depends_on:
            - web
            - redis
    
    celery_beat:
        build: .
        command: celery -A tech_trends beat --loglevel=info
        volumes:
            - .:/techtrends
        env_file: .env
        depends_on:
            - web
            - redis

