# Generated by Django 5.0.3 on 2024-08-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('category', models.CharField(choices=[('nepali', 'Nepali Tech News'), ('global', 'Global Tech News')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Trend',
        ),
    ]
