# Generated by Django 5.0.3 on 2024-08-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_technews_delete_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='technews',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
