# Generated by Django 5.0.3 on 2024-08-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0003_technews_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technews',
            name='category',
            field=models.CharField(choices=[('nepali', 'Nepali Tech News'), ('global', 'Global Tech News'), ('trending', 'Trending  News')], max_length=20),
        ),
    ]
