# Generated by Django 5.0.3 on 2024-08-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0004_alter_technews_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technews',
            name='category',
            field=models.CharField(choices=[('nepali', 'Nepali Tech News'), ('global', 'Global Tech News'), ('trending', 'Trending  News'), ('ronb', 'Routine Of Nepal Banda')], max_length=20),
        ),
    ]
