# Generated by Django 5.0.3 on 2025-03-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0005_alter_technews_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('nepali', 'Nepali Tech News'), ('global', 'Global Tech News'), ('trending', 'Trending  News'), ('ronb', 'Routine Of Nepal Banda')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('category', models.ManyToManyField(related_name='subscribers', to='trends.subscribedcategory')),
            ],
        ),
    ]
