# Generated by Django 5.0.3 on 2025-03-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribedcategory',
            old_name='category',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
