# Generated by Django 5.0.3 on 2025-03-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailApp', '0003_verificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
