# Generated by Django 5.0.3 on 2025-03-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailApp', '0004_subscribers_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
