# Generated by Django 5.0.3 on 2025-03-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailApp', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedcategory',
            name='name',
            field=models.CharField(choices=[('nepali', 'Nepali Tech News'), ('global', 'Global Tech News (Nepali)'), ('trending', 'Trending  News(Nepali)'), ('ronb', 'Routine Of Nepal Banda'), ('techcrunch', 'Tech Crunch'), ('newsapinewsapiorg', 'News API')], max_length=20, unique=True),
        ),
    ]
