# Generated by Django 5.0.3 on 2025-04-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailApp', '0008_verificationtoken_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='SuscribeStatus',
            field=models.BooleanField(default=False),
        ),
    ]
