# Generated by Django 5.0.3 on 2025-04-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailApp', '0009_alter_subscribers_suscribestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
