# Generated by Django 5.0.3 on 2025-04-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailApp', '0010_verificationtoken_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedcategory',
            name='name',
            field=models.CharField(choices=[('nepali', 'Nepali Tech News'), ('global', 'Global Tech News (Nepali)'), ('trending', 'Trending  News(Nepali)'), ('ronb', 'Routine Of Nepal Banda'), ('bbc', 'Tech BBC News'), ('newsapinewsapiorg', 'News API'), ('hackernews', 'Hacker News')], max_length=20, unique=True),
        ),
    ]
